# Generated by Django 5.2.5 on 2025-08-18 15:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foroshande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foroshande', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('request_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('MOVAFAGH', 'Movafagh'), ('NAMOVAFAGH', 'NaMovafagh')], default='NAMOVAFAGH', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('foroshande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharge_ha', to='core.foroshande')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.phonenumber')),
            ],
        ),
    ]
