# Generated by Django 5.2.5 on 2025-08-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foroshande',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
    ]
