# Generated by Django 5.2.5 on 2025-08-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_foroshande_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='mobile_number',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
