# Generated by Django 5.2.5 on 2025-08-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_phonenumber_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='mobile_number',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
