# Generated by Django 5.2.5 on 2025-08-18 15:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtebarTaghir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('MONTAZER', 'Montazer'), ('TAIED', 'Taied Shodeh'), ('RAD', 'Rad Shodeh')], default='MONTAZER', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('foroshande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etebar_taghirat', to='core.foroshande')),
            ],
        ),
        migrations.CreateModel(
            name='HesabEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('BES', 'Bes'), ('BED', 'Bed')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('ref_type', models.CharField(max_length=50)),
                ('ref_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('foroshande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hesab_entries', to='core.foroshande')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='amount_gt_0'), models.UniqueConstraint(fields=('foroshande', 'ref_type', 'ref_id'), name='unique_hesab_ref')],
            },
        ),
    ]
