# Generated by Django 5.2.5 on 2025-08-19 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesabdari', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hesabentry',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hesabentry',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_hesab_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hesabentry',
            name='status',
            field=models.CharField(choices=[('MONTAZER', 'Montazer'), ('TAIED', 'Taied Shodeh'), ('RAD', 'Rad Shodeh')], default='MONTAZER', max_length=10),
        ),
        migrations.DeleteModel(
            name='EtebarTaghir',
        ),
    ]
